services:
  drc.api:
    image: ${DOCKER_REGISTRY-}drcapi
    hostname: api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__redis=redis:6379
      - Apps__Gemini__Key=${Apps__Gemini__Key}
      - Apps__Meta__AppName=${Apps__Meta__AppName}
      - Apps__Meta__Key=${Apps__Meta__Key}
      - Apps__Meta__AccessToken=${Apps__Meta__AccessToken}
      - Apps__Meta__WhatsAppBusinessAccountId=${Apps__Meta__WhatsAppBusinessAccountId}
      - Apps__Meta__WhatsAppBusinessId=${Apps__Meta__WhatsAppBusinessId}
      - Apps__Meta__WhatsAppBusinessPhoneNumberId=${Apps__Meta__WhatsAppBusinessPhoneNumberId}
      - Jwt__Key=${Jwt__Key}
    volumes:
      - ./data:/app/data
    build:
      context: .
      dockerfile: DRC.Api/Dockerfile
    depends_on:
      redis:
        condition: service_healthy

  drc.app:
    image: ${DOCKER_REGISTRY-}drcapp
    hostname: app
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
      - services__api__http__0=http://api:8080
    build:
      context: .
      dockerfile: DRC.App/Dockerfile
    depends_on:
      - drc.api

  redis:
    image: redis:latest
    hostname: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  default:
    driver: bridge
    name: net
